// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBF02Cx9BuQWLNJPd199d7zNVSULAqrtz8',
    appId: '1:617811818721:web:bca08dadc93a5ee4dc1fa0',
    messagingSenderId: '617811818721',
    projectId: 'hedeaty-8d2ed',
    authDomain: 'hedeaty-8d2ed.firebaseapp.com',
    storageBucket: 'hedeaty-8d2ed.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBV7XXLWPKlbTMr8-vjoiQ3O3I1Jq0vFZY',
    appId: '1:617811818721:android:fb6ac360e39c3060dc1fa0',
    messagingSenderId: '617811818721',
    projectId: 'hedeaty-8d2ed',
    storageBucket: 'hedeaty-8d2ed.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxpxRTer9XG_TyCKJa9PsT2YA1N3Re1lg',
    appId: '1:617811818721:ios:77be92bb8ad23944dc1fa0',
    messagingSenderId: '617811818721',
    projectId: 'hedeaty-8d2ed',
    storageBucket: 'hedeaty-8d2ed.firebasestorage.app',
    iosBundleId: 'com.example.hedieatyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxpxRTer9XG_TyCKJa9PsT2YA1N3Re1lg',
    appId: '1:617811818721:ios:77be92bb8ad23944dc1fa0',
    messagingSenderId: '617811818721',
    projectId: 'hedeaty-8d2ed',
    storageBucket: 'hedeaty-8d2ed.firebasestorage.app',
    iosBundleId: 'com.example.hedieatyApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBF02Cx9BuQWLNJPd199d7zNVSULAqrtz8',
    appId: '1:617811818721:web:1ccccc941240af48dc1fa0',
    messagingSenderId: '617811818721',
    projectId: 'hedeaty-8d2ed',
    authDomain: 'hedeaty-8d2ed.firebaseapp.com',
    storageBucket: 'hedeaty-8d2ed.firebasestorage.app',
  );
}
